### ISSUE TITLE
Better monitoring for updates repo

### ISSUE THREAD

**Issue by foxx** [joyent/triton#212] opened 2016-09-06 14:17 UTC
Follow up from https://github.com/joyent/triton/issues/210.

The updates repo (`https://updates.joyent.com`) was showing as up and redirect to docs, however any attempts to download images resulted in a delayed 5xx error, as seen in https://github.com/joyent/triton/issues/210.

The joyent status [page](http://status.joyent.com/) did not indicate any problems, and it required a manual restart by @kusor to fix the issue.

**Comment by bahamat** [comment] 2016-09-06 23:05
This isn't a code issue, it's an operational issue for Joyent's cloud ops team. We're working on this internally, but we don't use github for operational issues so I'm closing this.

**Comment by foxx** [comment] 2016-09-06 23:06
@bahamas10 Yeah I wasn't sure where to best raise it, typically I've been raising them here and then someone creates an internal ticket. Should I be following a better procedure to report these sorts of issues?

**Closed by bahamat** 2016-09-06 23:05 UTC

**Comment by bahamat** [comment] 2016-09-06 23:29
@foxx Don't get me confused with @bahams10, he's someone else ;-)

There isn't anything necessarily wrong with reporting it here, and we do have an internal issue for it. We try to keep a discrete separation between code issues and operational issues. The only mechanism to report operational issues is for cloud or on-prem customers to file a ticket at help.joyent.com.

But at any rate, there really won't be any externally verifiable way to indicate whether or not the issue is resolved once it is fixed. So the best I can say is that it will definitely be addressed, but leaving the issue open doesn't serve any further purpose.

**Comment by foxx** [comment] 2016-09-06 23:31
Oops my bad, typo! No worries, for anything operational I'll submit a ticket instead. Thanks for quick response 👍
