### ISSUE TITLE
Compute Node (20150305T101223Z) PXE Boot Slow on (mswin) Vmware Player 7.1.0 build-2496824

### ISSUE THREAD

**Issue by naisanza** [joyent/triton#49] opened 2015-03-17 06:47 UTC
The SDC is running with the CoAL package, build: 20150305T101223Z. However, when booting over PXE with 6 CPU cores and 4GB of RAM, the process is extremely slow. It is like downloading over a 56K dial-up modem - each character of the grub bootloader "loads" one character per 1.5 seconds.

I've seen it boot over PXE normally once, after that it's always been slow. I'm not sure what's causing this issue.

**Comment by rmustacc** [comment] 2015-03-17 22:53
It sounds like your headnode is running in VMware. Is the compute node that you're booting to also in VMware?

We have a composite grub terminal that is usually able to send out to both the VGA and serial devices and the behavior you're seeing is usually caused by buggy firmware.

**Comment by jclulow** [comment] 2015-03-17 23:05
Hi, @naisanza.  When you say the bootloader loads, do you mean (as Robert supposes) that the grub menu text is drawn very slowly; or, rather, do you mean that once booting has begun, each period (`.`) character is drawn to the screen slowly and booting takes a long time?

**Comment by naisanza** [comment] 2015-03-17 23:23
@rmustacc correct! Both headnode and compute node are running in Vmware. It is strange because it worked smoothly, once.

@jclulow both! It loads character by character displaying the grub menu text, and similarly for everything afterwards.

**Comment by gprime66** [comment] 2015-03-27 16:08
@naisanza If you go to "Compatibility" and change the "Use Hardware Version" to 9 it runs at full speed (VMware 7.1.1)

**Comment by lloydde** [comment] 2015-03-27 16:40
@gprime66 that is a useful observation, you experienced the same symptom and that resolved it for you? Could you share more specifics of your configuration and the symptoms you were seeing?

**Comment by gprime66** [comment] 2015-03-27 17:39
I'm running on OS X with VMware 7.1.1. The head node and compute nodes are running as vm's. It's just a stock Coal install of the latest version. Version 10 and 9 of vmware's system hardware work, version 11 (the latest version) cause the pxe boot and operation to lag to the point where the system is unusable (even after boot up completes). The head node experiences no lag, it's triggered by something in the pxe image it seems.

**Comment by lloydde** [comment] 2015-03-27 21:07
@naisanza I suspect you can only adjust/upgrade the "virtual machine hardware versions" using the non-player products 
http://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1003746

What host OS and player version are you using?

**Comment by gprime66** [comment] 2015-03-27 21:53
OS X 10.10.3 with VMware fusion 7.1.1 (I don't know if there is a player version of OS X )

**Comment by gprime66** [comment] 2015-03-28 00:19
Looks like this on Mac

**Comment by jclulow** [comment] 2015-03-28 08:27
On 27 March 2015 at 14:00, Eric <notifications@github.com> wrote:
> @gprime66 Is it just me, or I haven't been able to find the "Compatibility" option? Please see screenshots below

Even if there is no GUI option to change that setting, you may be able
to open up the *.vmx file in a text editor and change the
"virtualHW.version" property to some lower (or higher) number.

-- 
Joshua M. Clulow
Software Engineer @ Joyent
mail: jmc@joyent.com

**Comment by naisanza** [comment] 2015-03-28 10:14
@jclulow That worked perfectly. @gprime66 Yup that's exactly what was needed to be done. Boot menu and system now loads and runs normally.

@all So would this be a VMware bug or SDC?

**Comment by lloydde** [comment] 2015-03-28 14:19
@naisanza what was the value before and after?

**Comment by naisanza** [comment] 2015-03-28 18:42
@lloydde Before: virtualHW.version = "11". After: virtualHW.version = "7"

I haven't tried "8" or "9" yet, but I took the same version that CoAL was running on. Like what @gprime66 says, version "11" did something that caused it not to work normally anymore

**Comment by discostur** [comment] 2016-03-31 00:55
Hi

i'm having the same problem, running both, CoaL and an extra compute-node on ESXi:

- CoaL HW.version=11
- ComputeNode HW.version=11

Grub menu is as fast as normal, but PXE Boot is taking about 2 hours / boot. Already tried different HW.versions for ComputeNode (7, 8, 9 and 10) but PXE is as slow as with HW.version=11.

Greets
Kilian

**Comment by jclulow** [comment] 2016-03-31 01:00
@discostur How are you PXE booting the virtual compute node?  Are you using the `Compute Node (PXE)` option in the grub menu provided on an SDC USB key image, or are you chainloading iPXE through the legacy PXE ROM that VMware provides?

**Comment by discostur** [comment] 2016-03-31 01:03
@jclulow i'm booting via CoaL USB-Image and then selecting the Compute Node (PXE) option from the grub menu

**Comment by jclulow** [comment] 2016-03-31 01:05
@discostur Can you try reconfiguring the SDC boot service to use HTTP booting?  Something like this:

```
dhcpd_svc=$(sdc-sapi /services?name=dhcpd | json -Ha uuid)
sapiadm update $dhcpd_svc metadata.http_pxe_boot=true
```

Then, in the `dhcpd0` zone make sure `config-agent` and `dhcpd` have restarted with the new setting.  You should, on the next boot of the CN, see a `http://` URL instead of a `tftp://` URL for the kernel and boot archives.  Hopefully this will be much faster than TFTP.

**Comment by discostur** [comment] 2016-03-31 13:23
@jclulow changing from tftp to http worked and it is really faster now, but it stops randomly and freezes. 
Tried it several times, the highest count i could get was 79% from the boot archives, then it stopped loading ...

**Comment by jclulow** [comment] 2016-03-31 19:11
@discostur Alright.  Can you try replacing the file `boot/ipxe.lkrn` on the compute node USB key with this test copy: https://us-east.manta.joyent.com/jmc/public/ipxe/resync201601/ipxe.lkrn

This is a test build of a much newer build of iPXE, and it might improve the situation with these more recent VMware versions.

**Comment by discostur** [comment] 2016-04-01 09:29
@jclulow Changed it with the version you posted and it works really smooth now. Booting up in <1min without any error via tftp. 

Thanks for your help ;)

**Comment by cheapRoc** [comment] 2017-05-19 20:33
Sounds like the issue was resolved successfully. Going to close this now.

**Closed by cheapRoc** 2017-05-19 20:33 UTC
